### ISSUE TITLE
Bad README

### ISSUE THREAD

**Issue by npxl32** [BluePlay-Games/blueplay-games.github.io#1]
The site will not "occasionally update", every time you commit to the branch that you specified in the settings, GitHub Pages will start a build in your website, you can see what's going on in the CI/CD Actions tab. I don't want to fork this just to change the README.

**Comment by saverofthewos** [comment]
CI/CD actions cost money after a certain amount of minutes, and yes, i have to make my fork up to date which is where the website is being hosted.

**Comment by npxl32** [comment]
CI/CD limit for free accounts is 2000 minutes. That's 33 hours per month. I don't think we'll use 33 hours per month, and I'm not sure if viewing CI counts as minutes of a CI/CD action being used.

**Comment by saverofthewos** [comment]
I don't think you understand what the readme means. The website is hosted on a different fork.

**Comment by npxl32** [comment]
oh
